import type { Metadata } from "next";
import { Work_Sans, Gabarito, Wix_Madefor_Text } from "next/font/google";
import "./globals.css";
import React from "react";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});
const wixMadeforText = Wix_Madefor_Text({
  variable: "--font-wix-madefor-text",
  subsets: ["latin"],
});
const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${wixMadeforText.variable} ${workSans.variable} ${gabarito.variable} antialiased font-[family-name:var(--font-work-sans)]`}
    >
    <div className={"gradient-bg"}>{children}</div>
    </body>
    </html>
  );
}
